### ISSUE TITLE
milestone: Going international!

### ISSUE THREAD

**Issue by xEdziu** [xEdziu/KeepMyPassword-Desktop#33]
## What needs to be done?

- [x] Prepare external (maybe xml) file for all string across this project
- [x] Move all strings to this file
- [x] Read values from this file in the scope of project
- [ ] Edit conf file to save language that currently is used
- [x] Find translators for languages!

**Comment by xEdziu** [comment]
@all-contributors please add @Kubis10 for test, ideas, bug and translation
