### ISSUE TITLE
milestone: Reconfigure conf file to support different languages

### ISSUE THREAD

**Issue by xEdziu** [xEdziu/KeepMyPassword-Desktop#40]
## What to do?

- [x] Add ComboBox for registration that will ask for language
- [ ] Add changing language option in settings
- [ ] Add mechanism for changing language in conf file

**Comment by xEdziu** [comment]
@all-contributors please add @xEdziu for code, design, security, projectManagement
